### ISSUE TITLE
Cannot run the project on mac

### ISSUE THREAD

**Issue by yp717** [IlyaKisil/dpm-coursework#8]
Cannot run the bash script on mac

## Expected Behaviour
project starts and works

## Current Behaviour
Below terminal output: 

(base) Yanniss-MBP:dpm-coursework-master yannispanagis$ sudo ./boostrap-venv.sh
Password:
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Applications/anaconda3/envs/dpm-coursework

  added / updated specs:
    - python=3.6.5

The following NEW packages will be INSTALLED:

  ca-certificates    pkgs/main/osx-64::ca-certificates-2021.1.19-hecd8cb5_1
  certifi            pkgs/main/osx-64::certifi-2020.12.5-py36hecd8cb5_0
  libcxx             pkgs/main/osx-64::libcxx-10.0.0-1
  libedit            pkgs/main/osx-64::libedit-3.1.20210216-h9ed2024_1
  libffi             pkgs/main/osx-64::libffi-3.2.1-h0a44026_1007
  ncurses            pkgs/main/osx-64::ncurses-6.2-h0a44026_1
  openssl            pkgs/main/osx-64::openssl-1.0.2u-h1de35cc_0
  pip                pkgs/main/osx-64::pip-21.0.1-py36hecd8cb5_0
  python             pkgs/main/osx-64::python-3.6.5-hc167b69_1
  readline           pkgs/main/osx-64::readline-7.0-h1de35cc_5
  setuptools         pkgs/main/osx-64::setuptools-52.0.0-py36hecd8cb5_0
  sqlite             pkgs/main/osx-64::sqlite-3.33.0-hffcf06c_0
  tk                 pkgs/main/osx-64::tk-8.6.10-hb0a8c7a_0
  wheel              pkgs/main/noarch::wheel-0.36.2-pyhd3eb1b0_0
  xz                 pkgs/main/osx-64::xz-5.2.5-h1de35cc_0
  zlib               pkgs/main/osx-64::zlib-1.2.11-h1de35cc_3

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate dpm-coursework
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Failed to import the site module
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
ValueError: source code string cannot contain null bytes
Failed to import the site module
Traceback (most recent call last):
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 541, in <module>
    main()
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 522, in main
    known_paths = addusersitepackages(known_paths)
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 282, in addusersitepackages
    user_site = getusersitepackages()
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 258, in getusersitepackages
    user_base = getuserbase() # this will also set USER_BASE
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/site.py", line 248, in getuserbase
    USER_BASE = get_config_var('userbase')
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/sysconfig.py", line 608, in get_config_var
    return get_config_vars().get(name)
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/sysconfig.py", line 587, in get_config_vars
    import _osx_support
  File "/Applications/anaconda3/envs/dpm-coursework/lib/python3.6/_osx_support.py", line 4, in <module>
    import re
ValueError: source code string cannot contain null bytes
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
(base) Yanniss-MBP:dpm-coursework-master yannispanagis$ conda activate dpm-coursework

## Steps to Reproduce

1.
2.

**Comment by IlyaKisil** [comment]
@yp717 Hi)

This should be fixed now. Syntax used in `bootstrap-venv.sh` assumed old version of Anaconda distribution, but since then 
```
source activate
source deactivate
```
got deprecated and replaced by 
```
conda activate
conda deactivate
```

Couple of things for the future:
* Don't use `sudo` for no good reason
* GitHub uses Markdown syntax, so a simple copy and paste from terminal might not work nicely when it gets rendered. For such situations, I'd suggest to surround your text with tripple backticks, e.g.

  \`\`\`
  your code goes here  
  \`\`\`

  Before submitting post, you can also checkout `Preview` tab 😉 

<img width="958" alt="Screen Shot 2021-03-27 at 00 56 51" src="https://user-images.githubusercontent.com/16823400/112705565-5dcf3a80-8e97-11eb-84a5-3536d32b8889.png">
